name: Tests
on: [push, pull_request]

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install
      - name: Run tests
        run: forge test -vvv
      - name: Generate coverage
        run: forge coverage
      - name: Checkout code
        uses: actions/checkout@v2
      # ... Generate LCOV files or download it from a different job
      - name: Report code coverage
        uses: uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: ./lcov.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}